//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_AutoGallery.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Auto_GalleryEntities : DbContext
    {
        public Auto_GalleryEntities()
            : base("name=Auto_GalleryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_Brands> Tbl_Brands { get; set; }
        public virtual DbSet<Tbl_Cars> Tbl_Cars { get; set; }
        public virtual DbSet<Tbl_Customers> Tbl_Customers { get; set; }
        public virtual DbSet<Tbl_Employee> Tbl_Employee { get; set; }
        public virtual DbSet<Tbl_Models> Tbl_Models { get; set; }
        public virtual DbSet<Tbl_Stores> Tbl_Stores { get; set; }
        public virtual DbSet<Tbl_Users> Tbl_Users { get; set; }
    }
}
