//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_AutoGallery.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Models
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Models()
        {
            this.Tbl_Cars = new HashSet<Tbl_Cars>();
        }
    
        public int Model_Id { get; set; }
        public string Model_Name { get; set; }
        public Nullable<int> Brand_Id { get; set; }
    
        public virtual Tbl_Brands Tbl_Brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Cars> Tbl_Cars { get; set; }
    }
}
