//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_AutoGallery.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Employee
    {
        public int Employee_Id { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Surname { get; set; }
        public string Employee_TC { get; set; }
        public string Employee_Phone { get; set; }
        public string Employee_Email { get; set; }
        public Nullable<int> Store_Id { get; set; }
    
        public virtual Tbl_Stores Tbl_Stores { get; set; }
    }
}
