//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_AutoGallery.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cars
    {
        public int Car_Id { get; set; }
        public string Car_Plate { get; set; }
        public string Car_Year { get; set; }
        public string Car_Color { get; set; }
        public string Car_Fuel { get; set; }
        public Nullable<decimal> Car_SalePrice { get; set; }
        public Nullable<decimal> Car_RentPrice { get; set; }
        public Nullable<int> Store_Id { get; set; }
        public Nullable<int> Model_Id { get; set; }
    
        public virtual Tbl_Models Tbl_Models { get; set; }
        public virtual Tbl_Stores Tbl_Stores { get; set; }
    }
}
